### ISSUE TITLE
[Feature]: 워크 스페이스 관련 작업

### ISSUE THREAD

**Issue by InHyeok-J** [TeamDiligence/CamAndEdit_Back#12]
## 기능 설명
- 워크스페이스 생성 및 조회
- 워크스페이스 초대 메일
- 워크스페이스 Redis 연동
- 워크스페이스 사용자 리스트 
- 워크스페이스 사용자 리스트 권한 수정 

## Tasks
- [x] 워크스페이스 생성 및 조회
- [ ] 워크스페이스 초대 메일
- [ ] 워크스페이스 Redis 연동
- [ ] 워크스페이스 사용자 리스트
- [ ] 워크스페이스 사용자 리스트 권한 수정
